---
- name: setup docker host
  vars:
    install_docker: yes
  import_playbook: docker_setup.yml

- name: Setup prometheus
  hosts: prometheus
  roles:
    - prometheus

- name: Setup grafana
  hosts: grafana
  roles:
    - grafana

- name: Setup crabby
  hosts: crabby,selenium_agent
  roles:
    - crabby
